module.exports = angular.module('toothpaste.toothwys', [])

.service('wysService', require('internal_components/wysiwyg/wysService.factory'))
.filter('convertBreakLine', require('internal_components/wysiwyg/convertBreakLine.filter'))
.directive('cmLinkModal', require('internal_components/wysiwyg/linkModal.directive'))
.directive('cmColorModal', require('internal_components/wysiwyg/colorModal.directive'))
.directive('cmFontSizeModal', require('internal_components/wysiwyg/fontSizeModal.directive'))
.directive('cmImgHandler', require('internal_components/wysiwyg/imgHandler.directive'))
.directive('cmUploadImg', require('internal_components/wysiwyg/uploadImg.directive'))
.directive('cmContainerEdit', require('internal_components/wysiwyg/containerEdit.directive'))
.directive('cmWysiwygHeader', require('internal_components/wysiwyg/wysiwygHeader.directive'))
.directive('cmWysiwygLink', require('internal_components/wysiwyg/wysiwygLink.directive'))
.directive('cmWysiwygButton', require('internal_components/wysiwyg/wysiwygButton.directive'))
.directive('cmWysiwygFooter', require('internal_components/wysiwyg/wysiwygFooter.directive'))
.directive('cmWysiwygSelect', require('internal_components/wysiwyg/wysiwygSelect.directive'))
.directive('cmWysiwygColorPicker', require('internal_components/wysiwyg/wysiwygColorPicker.directive'))
.directive('cmWysiwygBgColor', require('internal_components/wysiwyg/wysiwygBgColor.directive'))
.directive('cmWysiwyg', require('internal_components/wysiwyg/wysiwyg.directive'));
